[versions]
gradle = "7.4.2"
kotlin-gradle-plugin = "1.8.10"
min-sdk = "23"
compile-sdk = "33"
target-sdk = "33"
desugar-jdk = "1.1.6"
kotlin-compiler-extension-version = "1.3.2"
spotless = "6.12.0"

android-appcompat = "1.5.1"
android-material = "1.7.0"
android-navigation = "2.5.3"
android-constraintlayout = "2.1.4"
lifecycle-ktx = "2.5.1"
activity-ktx = "1.6.1"
core-ktx = "1.9.0"

activity-compose = "1.6.1"
compose-ui = "1.3.1"
accompanist = "0.27.0"

coroutines = "1.6.4"
turbine = "0.12.1"

hilt = "2.44.2"
hilt-navigation-compose = "1.0.0"

camerax = "1.2.0-beta02"
mlkit-barcode-scanning = "18.1.0"

security-crypto-stable = "1.0.0"
security-crypto-ktx = "1.1.0-alpha03"
androidx-biometrics = "1.1.0"

okta-bom = "1.1.1"

kotlin-stdlib = "1.7.20"
timber = "5.0.1"

kotlin-onetimepassword = "2.4.0"
commons-codec = "1.15"

# Testing lib versions
junit = "4.13.2"
jackson = "2.14.0"
truth = "1.1.3"
mockk = "1.13.2"
androidx-test = "1.5.0"
androidx-test-runner = "1.5.1"
androidx-test-orchestrator = "1.4.2"
androidx-test-espresso = "3.5.0"
androidx-test-ext = "1.1.4"
androidx-test-fragment = "1.5.4"
androidx-test-uiautomator = "2.2.0"
robolectric = "4.9"
okta-http-okhttp = "1.3.2"
okta-management-sdk = "8.2.2"

[libraries]
gradle = { module = "com.android.tools.build:gradle", version.ref = "gradle" }
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin-gradle-plugin" }
desugar-jdk = { module = "com.android.tools:desugar_jdk_libs", version.ref = "desugar-jdk" }
spotless = { module = "com.diffplug.spotless:spotless-plugin-gradle", version.ref = "spotless" }

android-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "android-appcompat"}
android-material = { module = "com.google.android.material:material", version.ref = "android-material" }
android-navigation-ui = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "android-navigation" }
android-navigation-fragment = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "android-navigation" }
android-navigation-safe-args = { module = "androidx.navigation:navigation-safe-args-gradle-plugin", version.ref = "android-navigation" }
android-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "android-constraintlayout" }
lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle-ktx"}
lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycle-ktx" }
activity-ktx = { module = "androidx.activity:activity-ktx", version.ref = "activity-ktx" }
core-ktx = { module = "androidx.core:core-ktx", version.ref = "core-ktx" }

activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activity-compose" }
compose-ui = { module = "androidx.compose.ui:ui", version.ref = "compose-ui" }
compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "compose-ui" }
compose-material = { module = "androidx.compose.material:material", version.ref = "compose-ui" }
accompanist-permissions = { module = "com.google.accompanist:accompanist-permissions", version.ref = "accompanist" }
navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "android-navigation" }

compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose-ui" }
compose-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest", version.ref = "compose-ui" }
compose-ui-test-junit = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "compose-ui" }

coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }
turbine = { module = "app.cash.turbine:turbine", version.ref = "turbine" }

hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "hilt" }
hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hilt-navigation-compose" }

hilt-android-testing = { module = "com.google.dagger:hilt-android-testing", version.ref = "hilt" }
hilt-compiler-testing = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hilt" }

camera-core = { module = "androidx.camera:camera-core", version.ref = "camerax" }
camera-camera2 = { module = "androidx.camera:camera-camera2", version.ref = "camerax" }
camera-lifecycle = { module = "androidx.camera:camera-lifecycle", version.ref = "camerax" }
camera-video = { module = "androidx.camera:camera-video", version.ref = "camerax" }
camera-view = { module = "androidx.camera:camera-view", version.ref = "camerax" }
camera-extensions = { module = "androidx.camera:camera-extensions", version.ref = "camerax" }
camera-mlkit-vision = { module = "androidx.camera:camera-mlkit-vision", version.ref = "camerax" }
mlkit-barcode-scanning = { module = "com.google.android.gms:play-services-mlkit-barcode-scanning", version.ref = "mlkit-barcode-scanning" }

security-crypto-ktx = { module = "androidx.security:security-crypto-ktx", version.ref = "security-crypto-ktx" }
security-crypto-stable = { module = "androidx.security:security-crypto", version.ref = "security-crypto-stable" }
androidx-biometrics = { module = "androidx.biometric:biometric", version.ref = "androidx-biometrics" }

okta-bom = { module = "com.okta.kotlin:bom", version.ref = "okta-bom" }
okta-auth-foundation-bootstrap = { module = "com.okta.kotlin:auth-foundation-bootstrap" }
okta-web-authentication-ui = { module = "com.okta.kotlin:web-authentication-ui" }

kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin-stdlib" }
timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }

kotlin-onetimepassword = { module = "dev.turingcomplete:kotlin-onetimepassword", version.ref = "kotlin-onetimepassword" }
commons-codec = { group = "commons-codec", name = "commons-codec", version.ref = "commons-codec" }

# Testing libs
junit = { module = "junit:junit", version.ref = "junit" }
jackson-dataformat-yml = { module = "com.fasterxml.jackson.dataformat:jackson-dataformat-yaml", version.ref = "jackson" }
truth = { module = "com.google.truth:truth", version.ref = "truth" }
robolectric = { module = "org.robolectric:robolectric", version.ref = "robolectric" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }

androidx-test-core = { module = "androidx.test:core", version.ref = "androidx-test" }
androidx-test-core-ktx = { module = "androidx.test:core-ktx", version.ref = "androidx-test" }
androidx-test-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "androidx-test-espresso"}
androidx-test-espresso-contrib = { module = "androidx.test.espresso:espresso-contrib", version.ref = "androidx-test-espresso"}
androidx-test-espresso-intents = { module = "androidx.test.espresso:espresso-intents", version.ref = "androidx-test-espresso"}
androidx-test-ext-junit = { module = "androidx.test.ext:junit", version.ref = "androidx-test-ext" }
androidx-test-ext-junit-ktx = { module = "androidx.test.ext:junit-ktx", version.ref = "androidx-test-ext" }
androidx-test-fragment = { module = "androidx.fragment:fragment-testing", version.ref = "androidx-test-fragment" }
androidx-test-navigation = { module = "androidx.navigation:navigation-testing", version.ref = "android-navigation" }
androidx-test-orchestrator = { module = "androidx.test:orchestrator", version.ref = "androidx-test-orchestrator" }
androidx-test-runner = { module = "androidx.test:runner", version.ref = "androidx-test-runner" }
androidx-test-rules = { module = "androidx.test:rules", version.ref = "androidx-test" }
androidx-test-uiautomator = { module = "androidx.test.uiautomator:uiautomator", version.ref = "androidx-test-uiautomator" }

okta-management-sdk = { module = "com.okta.sdk:okta-sdk-impl", version.ref = "okta-management-sdk" }
okta-http-okhttp = { module = "com.okta.commons:okta-http-okhttp", version.ref = "okta-http-okhttp" }

[bundles]
# Common android imports
android = [
    "android-appcompat",
    "android-material",
    "android-navigation-ui",
    "android-navigation-fragment",
    "android-constraintlayout",
    "lifecycle-runtime-ktx",
    "lifecycle-viewmodel-ktx",
    "activity-ktx",
    "core-ktx",
]
camerax = [
    "camera-core",
    "camera-camera2",
    "camera-lifecycle",
    "camera-video",
    "camera-view",
    "camera-extensions",
    "camera-mlkit-vision",
]
compose-ui = [
    "activity-compose",
    "compose-ui",
    "compose-ui-tooling-preview",
    "compose-material",
    "accompanist-permissions",
    "navigation-compose",
]
compose-debug = [
    "compose-ui-tooling",
    "compose-ui-test-manifest",
]
coroutines = [
    "coroutines-core",
    "coroutines-android",
]
unit-testing = [
    "junit",
    "truth",
    "robolectric",
    "mockk",
    "coroutines-test",
    "turbine",
]
android-instrumentation-testing = [
    "androidx-test-core",
    "androidx-test-core-ktx",
    "androidx-test-espresso-core",
    "androidx-test-espresso-contrib",
    "androidx-test-espresso-intents",
    "androidx-test-ext-junit",
    "androidx-test-ext-junit-ktx",
    "androidx-test-navigation",
    "androidx-test-runner",
    "androidx-test-rules",
    "androidx-test-uiautomator",
]
okta-testing = [
    "okta-management-sdk",
    "okta-http-okhttp",
]
